import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_client = Groq(api_key=os.environ["GROQ_API_KEY"])

_SYSTEM_PROMPT = """You assess whether a piece of text was written by a human or \
generated by an AI language model. Judge holistic semantic and stylistic \
coherence: human writing tends to have idiosyncrasy, imperfection, and lived \
specificity; AI-generated text tends to be smoothed-out and generically \
coherent.

Respond with ONLY a JSON object, no other text, in this exact shape:
{"llm_score": <float between 0 and 1, 1 = confident AI, 0 = confident human>, \
"justification": "<one sentence>"}
"""


def classify_with_llm(text):
    response = _client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0,
    )
    content = response.choices[0].message.content
    parsed = json.loads(content)
    score = float(parsed["llm_score"])
    return max(0.0, min(1.0, score))
